module.exports = [
  [/[a-z]+/, {
    type: 'match',
    offset: 0,
    text: '[a-z]+',
    body: [
      {
        type: 'quantified',
        offset: 0,
        text: '[a-z]+',
        body: {
          type: 'charset',
          offset: 0,
          text: '[a-z]',
          invert: false,
          body: [{
            type: 'range',
            offset: 1,
            text: 'a-z',
            start: {
              type: 'literal',
              offset: 1,
              text: 'a',
              body: 'a',
              escaped: false
            },
            end: {
              type: 'literal',
              offset: 3,
              text: 'z',
              body: 'z',
              escaped: false
            }
          }]
        },
        quantifier: {
          type: 'quantifier',
          offset: 5,
          text: '+',
          min: 1,
          max: Infinity,
          greedy: true
        }
      }
    ]
  }],
  [/a|bc*/, {
    type: 'alternate',
    offset: 0,
    text: 'a|bc*',
    left: {
      type: 'match',
      offset: 0,
      text: 'a',
      body:[{
        type: 'literal',
        offset: 0,
        text: 'a',
        body: 'a',
        escaped: false
      }]
    },
    right: {
      type: 'match',
      offset: 2,
      text: 'bc*',
      body: [
        {
          type: 'literal',
          offset: 2,
          text: 'b',
          body: 'b',
          escaped: false
        },
        {
          type: 'quantified',
          offset: 3,
          text: 'c*',
          body: {
            type: 'literal',
            offset: 3,
            text: 'c',
            body: 'c',
            escaped: false
          },
          quantifier: {
            type: 'quantifier',
            offset: 4,
            text: '*',
            min: 0,
            max: Infinity,
            greedy: true
          }
        }
      ]
    }
  }],
  [/\n\b[\-]/, {
    type: 'match',
    offset: 0,
    text: '\\n\\b[\\-]',
    body: [
      {
        type: 'line-feed',
        offset: 0,
        text: '\\n'
      },
      {
        type: 'word-boundary',
        offset: 2,
        text: '\\b'
      },
      {
        type: 'charset',
        offset: 4,
        text: '[\\-]',
        invert: false,
        body: [{
          type: 'literal',
          offset: 5,
          text: '\\-',
          body: '-',
          escaped: true
        }]
      }
    ]
  }],
  [/\u1Af/, {
    type: 'match',
    offset: 0,
    text: '\\u1Af',
    body: [{
      type: 'unicode',
      offset: 0,
      text: '\\u1Af',
      code: '1AF'
    }]
  }],
  [/again and again/,{ type: 'match',
    offset: 0,
    text: 'again and again',
    body:
     [ { type: 'literal',
         offset: 0,
         text: 'a',
         body: 'a',
         escaped: false },
       { type: 'literal',
         offset: 1,
         text: 'g',
         body: 'g',
         escaped: false },
       { type: 'literal',
         offset: 2,
         text: 'a',
         body: 'a',
         escaped: false },
       { type: 'literal',
         offset: 3,
         text: 'i',
         body: 'i',
         escaped: false },
       { type: 'literal',
         offset: 4,
         text: 'n',
         body: 'n',
         escaped: false },
       { type: 'literal',
         offset: 5,
         text: ' ',
         body: ' ',
         escaped: false },
       { type: 'literal',
         offset: 6,
         text: 'a',
         body: 'a',
         escaped: false },
       { type: 'literal',
         offset: 7,
         text: 'n',
         body: 'n',
         escaped: false },
       { type: 'literal',
         offset: 8,
         text: 'd',
         body: 'd',
         escaped: false },
       { type: 'literal',
         offset: 9,
         text: ' ',
         body: ' ',
         escaped: false },
       { type: 'literal',
         offset: 10,
         text: 'a',
         body: 'a',
         escaped: false },
       { type: 'literal',
         offset: 11,
         text: 'g',
         body: 'g',
         escaped: false },
       { type: 'literal',
         offset: 12,
         text: 'a',
         body: 'a',
         escaped: false },
       { type: 'literal',
         offset: 13,
         text: 'i',
         body: 'i',
         escaped: false },
       { type: 'literal',
         offset: 14,
         text: 'n',
         body: 'n',
         escaped: false } ] }],
  [/(a)(b)(?:c)(d)/, { type: 'match',
    offset: 0,
    text: '(a)(b)(?:c)(d)',
    body:
     [ { type: 'capture-group',
         offset: 1,
         text: 'a',
         body:
          { type: 'match',
            offset: 1,
            text: 'a',
            body:
             [ { type: 'literal',
                 offset: 1,
                 text: 'a',
                 body: 'a',
                 escaped: false } ] },
         index: 1 },
       { type: 'capture-group',
         offset: 4,
         text: 'b',
         body:
          { type: 'match',
            offset: 4,
            text: 'b',
            body:
             [ { type: 'literal',
                 offset: 4,
                 text: 'b',
                 body: 'b',
                 escaped: false } ] },
         index: 2 },
       { type: 'non-capture-group',
         offset: 7,
         text: '?:c',
         body:
          { type: 'match',
            offset: 9,
            text: 'c',
            body:
             [ { type: 'literal',
                 offset: 9,
                 text: 'c',
                 body: 'c',
                 escaped: false } ] } },
       { type: 'capture-group',
         offset: 12,
         text: 'd',
         body:
          { type: 'match',
            offset: 12,
            text: 'd',
            body:
             [ { type: 'literal',
                 offset: 12,
                 text: 'd',
                 body: 'd',
                 escaped: false } ] },
         index: 3 } ] }],
  [/\cm/, {
    type: 'match',
    offset: 0,
    text: '\\cm',
    body: [{
      type: 'control-character',
      offset: 0,
      text: '\\cm',
      code: 'M'
    }]
  }],
  ['/@(?<profile>\\w+)/', { type: 'match',
  offset: 0,
  text: '@(?<profile>\\w+)',
  body:
   [ { type: 'literal',
       offset: 0,
       text: '@',
       body: '@',
       escaped: false },
     { type: 'named-group',
       offset: 2,
       text: '?<profile>\\w+',
       body:
        { type: 'match',
          offset: 12,
          text: '\\w+',
          body:
           [ { type: 'quantified',
               offset: 12,
               text: '\\w+',
               body: { type: 'word', offset: 12, text: '\\w' },
               quantifier:
                { type: 'quantifier',
                  offset: 14,
                  text: '+',
                  min: 1,
                  max: Infinity,
                  greedy: true } } ] },
       name: 'profile' } ] }],
  ['/\\(([^()]|(?R))*\\)/', { type: 'match',
  offset: 0,
  text: '\\(([^()]|(?R))*\\)',
  body:
   [ { type: 'literal',
       offset: 0,
       text: '\\(',
       body: '(',
       escaped: true },
     { type: 'quantified',
       offset: 2,
       text: '([^()]|(?R))*',
       body:
        { type: 'capture-group',
          offset: 3,
          text: '[^()]|(?R)',
          body:
           { type: 'alternate',
             offset: 3,
             text: '[^()]|(?R)',
             left:
              { type: 'match',
                offset: 3,
                text: '[^()]',
                body:
                 [ { type: 'charset',
                     offset: 3,
                     text: '[^()]',
                     invert: true,
                     body:
                      [ { type: 'literal',
                          offset: 5,
                          text: '(',
                          body: '(',
                          escaped: false },
                        { type: 'literal',
                          offset: 6,
                          text: ')',
                          body: ')',
                          escaped: false } ] } ] },
             right:
              { type: 'match',
                offset: 9,
                text: '(?R)',
                body:
                 [ { type: 'logic-nesting',
                     offset: 10,
                     text: '?R',
                     body: { type: 'match', offset: 12, text: '', body: [] } } ] } },
          index: 1 },
       quantifier:
        { type: 'quantifier',
          offset: 14,
          text: '*',
          min: 0,
          max: Infinity,
          greedy: true } },
     { type: 'literal',
       offset: 15,
       text: '\\)',
       body: ')',
       escaped: true } ] }],
  ['/(?<=@)\\w+/', { type: 'match',
  offset: 0,
  text: '(?<=@)\\w+',
  body:
   [ { type: 'positive-lookback',
       offset: 1,
       text: '?<=@',
       body:
        { type: 'match',
          offset: 4,
          text: '@',
          body:
           [ { type: 'literal',
               offset: 4,
               text: '@',
               body: '@',
               escaped: false } ] } },
     { type: 'quantified',
       offset: 6,
       text: '\\w+',
       body: { type: 'word', offset: 6, text: '\\w' },
       quantifier:
        { type: 'quantifier',
          offset: 8,
          text: '+',
          min: 1,
          max: Infinity,
          greedy: true } } ] }],
  ['/(?<!\\w)@\\w+/', { type: 'match',
  offset: 0,
  text: '(?<!\\w)@\\w+',
  body:
   [ { type: 'negative-lookback',
       offset: 1,
       text: '?<!\\w',
       body:
        { type: 'match',
          offset: 4,
          text: '\\w',
          body: [ { type: 'word', offset: 4, text: '\\w' } ] } },
     { type: 'literal',
       offset: 7,
       text: '@',
       body: '@',
       escaped: false },
     { type: 'quantified',
       offset: 8,
       text: '\\w+',
       body: { type: 'word', offset: 8, text: '\\w' },
       quantifier:
        { type: 'quantifier',
          offset: 10,
          text: '+',
          min: 1,
          max: Infinity,
          greedy: true } } ] }],
]
